model: model.predictor.baseline_clgrl.SuperpixelsBaseline
experiment: experiment.continual_lwf_task.ContinualLwFTask
n_tasks: 5
higher_results_are_better: True
log_every: 1
dataset-getter: data.provider.ContinualSplitDataProvider
device: cpu
num_dataloader_workers: 0  # > 0 only with --debug option and GPU device
pin_memory: True  # True only with --debug option and GPU device
grid:
  supervised_config:
    checkpoint: True
    num_layers:
      - 4
    hidden_units:
      - 64
      - 128
    batch_size:
      - 128
    epochs:
      - 200
    optimizer:
      -
        class_name: training.callback.optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.Adam
          lr:
            - 0.001
          weight_decay: 0.
    loss:
      -
        class_name: training.callback.loss.LwFLoss
        args:
          alpha:
            - 0.5
            - 1.0
            - 2.0
          distillation_temperature:
            - 0.5
            - 1
            - 2
          mode:
            - last
            - sum
    scorer:
      - training.callback.score.MulticlassAccuracyScore
    predictor:
      - null
    wrapper:
      - training.engine.TrainingEngine
    gradient_clipping:
      - null
    dropout:
      - 0.
    early_stopper:
      -
        class_name:
          - training.callback.early_stopping.PatienceEarlyStopper
        args:
          patience:
            - 20
          # Should be the name of the main_scorer in MultiScore
          monitor: validation_Multiclass Accuracy # (train_,validation_)[name_of_the_scorer_or_loss_to_monitor]
          mode: max
          checkpoint: True
    plotter:
      - training.callback.plotter.Plotter
    shuffle:
      - True
